### ISSUE TITLE
All findViewById references should be private fields of the class

### ISSUE THREAD

**Issue by KyleBastien** [mcontado/Android-HelloWorld#1]
https://github.com/mcontado/Android-HelloWorld/blob/4dbfba32f9ace0a09b37b54211668e75f79be4e0/app/src/main/java/com/example/myfirstapp/MainActivity.java#L16

Nitpick: This button should be a private field of the MainActivity class. This will allow you to reference this Button reference in other methods of your class in the future, which will be advantageous.

**Comment by mcontado** [comment]
Addressed
