### ISSUE TITLE
Try using android:onClick like I showed in class, a bit easier than what you're doing here

### ISSUE THREAD

**Issue by KyleBastien** [mcontado/Android-HelloWorld#3]
https://github.com/mcontado/Android-HelloWorld/blob/4291e4fa4d80dbf18798362242cbff7c81a0f08b/app/src/main/java/com/example/myfirstapp/MainActivity.java#L61

**Comment by mcontado** [comment]
Addressed this issue: 
https://github.com/mcontado/Android-HelloWorld/blob/6d4fc69e1308f5b263b57e9a66b084bd716fb7b0/app/src/main/java/com/example/myfirstapp/MainActivity.java#L64
