### ISSUE TITLE
Small bug: This only takes into account Year, not date in calculating age.

### ISSUE THREAD

**Issue by KyleBastien** [mcontado/Android-HelloWorld#4]
https://github.com/mcontado/Android-HelloWorld/blob/4291e4fa4d80dbf18798362242cbff7c81a0f08b/app/src/main/java/com/example/myfirstapp/MainActivity.java#L76

For example I was born on June 21st 1993, so this says I'm 25. But, my birthday hasn't passed this year, so I'm only 24 actually.

**Comment by mcontado** [comment]
Addressed this comment by having a private method to calculate the age:  https://github.com/mcontado/Android-HelloWorld/blob/5a46b3f0c6a059571b9f7010743b877497854caf/app/src/main/java/com/example/myfirstapp/MainActivity.java#L100
